name: appointment_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  image_picker: ^1.0.7 
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geocoding: ^2.1.0
  path: ^1.8.3
  shared_preferences: ^2.2.2 
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/google_logo.png
    - lib/assets/banner.png
